#!/usr/bin/env python3
"""Regenerate docs/MANIFESTS.md from the build lists and Repak manifests in this repo.

  py -3 tools/manifest_index.py
"""
import json
import re
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "MANIFESTS.md"

COMMENT_RE = re.compile(r'(?<!:)//[^\n]*$', re.M)


def load(path):
    txt = path.read_text(encoding="utf-8", errors="replace")
    txt = COMMENT_RE.sub("", txt)
    txt = re.sub(r",(\s*[}\]])", r"\1", txt)
    return json.loads(txt)


def build_lists():
    rows = []
    for bl in sorted(ROOT.glob("build_list*.json")) + sorted((ROOT / "s30_unified").glob("build_list*.json")):
        try:
            d = load(bl)
        except Exception as e:  # noqa: BLE001
            rows.append((bl.relative_to(ROOT).as_posix(), None, str(e)))
            continue
        rows.append((bl.relative_to(ROOT).as_posix(), d, None))
    return rows


def manifest_rows():
    rows = []
    for mf in sorted(ROOT.rglob("*.json")):
        if mf.name.startswith("build_list") or mf.parent.name == "tools":
            continue
        try:
            d = load(mf)
        except Exception:  # noqa: BLE001
            continue
        files = d.get("files") if isinstance(d, dict) else None
        if not isinstance(files, list):
            continue
        types = Counter(f.get("_type", "?") for f in files if isinstance(f, dict))
        rows.append({
            "path": mf.relative_to(ROOT).as_posix(),
            "name": d.get("name", mf.stem),
            "version": d.get("version"),
            "count": len(files),
            "types": ", ".join(f"{t}:{n}" for t, n in types.most_common()),
            "mandatory": d.get("streamFileMandatory", ""),
            "optional": d.get("streamFileOptional", ""),
        })
    return rows


def main():
    lines = ["# Manifest index", "", "Generated by `tools/manifest_index.py`.", ""]

    lines += ["## Build lists", "", "| build list | dedi | outputDir | paks |", "|---|---|---|---|"]
    for path, d, err in build_lists():
        if err:
            lines.append(f"| `{path}` | | | parse error: {err} |")
            continue
        paks = "<br>".join(f"`{p}`" for p in d.get("paks", []))
        lines.append(f"| `{path}` | {'yes' if d.get('dedi') else ''} | `{d.get('outputDir', '')}` | {paks} |")

    lines += ["", "## Manifests", "",
              "| manifest | name | ver | assets | types | mandatory starpak | optional starpak |",
              "|---|---|---|---|---|---|---|"]
    for r in manifest_rows():
        lines.append(f"| `{r['path']}` | {r['name']} | {r['version']} | {r['count']} | {r['types']} "
                     f"| `{r['mandatory']}` | `{r['optional']}` |")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT).as_posix()}")


if __name__ == "__main__":
    main()
